ktutil: Avoid even arithmetic on res after realloc(res, ...).
heimdal/heimdal pull request #1165
Opened 2023-06-20 23:51 UTC by riastradh

Under C99, Sec 6.2.4, paragraph 2:

> The value of a pointer becomes indeterminate when the object it points to reaches the end of its lifetime.

'Indeterminate' (3.17.2) includes a trap representation, and any reference to a trap representation is undefined behaviour.  Thus, after realloc(res, ...) succeeds, any reference to res (or p) is undefined behaviour.

So, instead of using `p - res` after res has been freed, use the existing name for the value we know it has now: len.  (We could also use alloced because p == end in this branch, and end = res + alloced, and p = res + len.  Of course, we would have to move it up a line to before we update alloced to have a different value.)

fix https://github.com/heimdal/heimdal/issues/1164

2023-11-02 20:49 UTC, abartlet requested changes

2023-11-02 20:49 UTC, abartlet commented on admin/add.c
> +            p = tmp + alloced;
This really doesn't look right.  Shouldn't it be `p = tmp + len`?

2023-11-02 21:31 UTC, abartlet commented on admin/add.c
> +            p = tmp + alloced;
Yes, it would be much clearer, as we can clearly see len incrementing on line 195

2023-11-07 20:20 UTC, merged

2023-11-07 20:20 UTC, nicowilliams commented
Thanks!