Reintroduce krb5_addlog_func() as as supported API
heimdal/heimdal pull request #786
Opened 2021-06-30 04:40 UTC by abartlet

krb5_addlog_func() is used by Samba to obtain Kerberos log messages
and place them into the Samba logs.

Providing a hook down to the heim_addlog_func() is less disruptive
than needing to call multiple different APIs as Samba compiles
both with an included copy of Heimdal and against a system
Heimdal (when not an AD DC).

This API was deprecated and stubbed out in March 2020 by
ea90ca86664c73fb8d415f3cc7baacdf8a6dd685 and was previously
stable until 0c869176f4122fb04b60453d1210fa6b7630624f
(which looks like it should have been part of
e44c680d8efbb20ab1980e604178eb9d0d38cdcb).

Despite the need for the extra argument, which we add a test for,
Samba would prefer to keep the krb5_addlog_func() facility,
so this adds it back.

Selected from patches by Stefan Metzmacher <metze@samba.org>
in his master-heimdal branch at:
https://git.samba.org/?p=metze/samba/wip.git;a=commitdiff;h=40d98064f44c54b42420ed81f7f39e5469aefaa8#patch4
https://git.samba.org/?p=metze/samba/wip.git;a=shortlog;h=refs/heads/master-heimdal

Signed-off-by: Andrew Bartlett <abartlet@samba.org>

2021-06-30 04:48 UTC, lhoward commented
@nicowilliams will need to look at this

2021-08-06 02:52 UTC, lhoward requested changes

2021-08-06 02:52 UTC, lhoward commented on lib/krb5/log.c
> +static void HEIM_CALLCONV krb5_addlog_func_wrapper_log(heim_context hcontext,
Sorry to be picky, could you please put `krb5_addlog_func_wrapper_log` on a new line?

2021-08-06 02:52 UTC, lhoward commented on lib/krb5/log.c
> +	krb5_context context;
4 spaces

2021-08-06 02:52 UTC, lhoward commented on lib/krb5/log.c
> +	return heim_enomem(context->hcontext);
`krb5_enomem(context)`

2021-08-08 21:36 UTC, abartlet commented
The AppVeyor build failed, it the Windows build racy?  The changes built on LInux, but a CI pass would be nice.

2021-08-08 22:52 UTC, lhoward commented
It’s racy and not working reliably for anyone unfortunately.

2021-08-09 01:42 UTC, abartlet commented
Do I need to re-push or re-trigger it somehow?

2021-08-09 01:43 UTC, lhoward commented
We need to fix the underlying race condition which is no doubt a dependency error in NTMakefile (in lib/gssapi). Not sure how to re-push or re-trigger. cc @jaltman

2021-08-09 13:28 UTC, lhoward commented
Fixed in c953bc5e7958eba002bbf00a65f8baec0ac28692

2021-08-09 13:28 UTC, closed without merging

2021-08-12 05:37 UTC, kaduk commented
> Not sure how to re-push or re-trigger.

I believe close+reopen will re-trigger the CI run.