Support split gss tokens
heimdal/heimdal pull request #798
Opened 2021-08-04 21:25 UTC by elric1

There are a number of other commits in this pull request to support the main change, but we present the meat of the commit message for said main change's commit:

```
    gss_accept_sec_context: support reassembling split tokens.

    Microsoft will sometimes split GSS tokens when they exceed a certain
    size in some protocols.  This is specified in

            [MS-SPNG]: Simple and Protected GSS-API Negotiation
            Mechanism (SPNEGO) Extension

    https://winprotocoldoc.blob.core.windows.net/productionwindowsarchives/MS-SPNG/%5bMS-SPNG%5d.pdf

    sections 3.1.5.4 to 3.1.5.9.

    We extend gss_accept_sec_context() to recognise partial tokens and
    to accumulate the fragments until an entire token is available to
    be processed.  If the entire token is not yet available,
    GSS_S_CONTINUE_NEEDED is returned with a zero length output token.
    This is specified in RFC2744 page 25-26 to indicate that no reply
    need be sent.

    We include updates to the test framework to test split tokens when
    using SPNEGO.
```

2021-08-04 21:53 UTC, lhoward commented
It looks like no changes are required to the SPNEGO mech, is that correct? I ask as I have in #796 added support for exporting partially established SPNEGO contexts (to use with GSS pre-authentication on the KDC) and wonder what the interaction would be with this.

2021-08-04 21:56 UTC, elric1 commented
@lukeh: Thanks for asking! I need to fix SPNEGO, but just before I did it, @nicowilliams suggested talking to you about it first. So, I'd like the export of partially established SPNEGO contexts to work, but I didn't implement it. And so there should be no conflicts with your work.

2021-08-05 12:32 UTC, lhoward reviewed
LGTM!

2021-08-05 12:32 UTC, lhoward commented on lib/gssapi/mech/gss_accept_sec_context.c
> +         *
Is the comment finished?

2021-08-06 22:32 UTC, lhoward commented on lib/gssapi/mech/gss_accept_sec_context.c
> +                if (der_get_length(p+1, len-1, &ctx->gc_target_len, &l) != 0)
If I was being picky, whitespace around p+1 but...

2021-08-07 03:47 UTC, lhoward requested changes

2021-08-07 03:47 UTC, lhoward commented on lib/krb5/store.c
> +{
Two issues here: firstly, 32-bit negative numbers (e.g. ~0UL) are sign extended which makes the encoding less efficient. We could add a size argument to `pack_int()` and mask `value` off, or perhaps there is another approach.

Secondly, encoding ~0ULL is not possible – the decoder parses it as two integers. We will need to expand the number of bits used to encode the length. If the length can never be zero, then we can encode one less than the length, but we still need to account for `length - 1 == 8` for ~0ULL.

Cc @nicowilliams

2021-08-07 03:47 UTC, lhoward commented on lib/krb5/store.c
> +        ret = sp->fetch(sp, v + 1, len - 1);
We need to check `len > 0` otherwise we have an overflow.

2021-08-07 03:47 UTC, lhoward commented
If you resolve the issues with a separate commit I can cherry-pick, I have a local branch that resolves the conflicts in `test_context.c`. Although I'm sure you can do that yourself too!

2021-08-07 08:56 UTC, lhoward commented
Fixed, merged.

2021-08-07 08:56 UTC, closed without merging