heimdal:kdc: Avoid uninitialised data being logged
heimdal/heimdal pull request #870
Opened 2021-12-03 04:40 UTC by abartlet

Another patch by @josephsutton1:

If a function calls unparse_flags() to convert a KDCOptions value into a
string when the 'validate' flag is set, KDCOptions2int() will return 1
<< 31, which becomes −2147483648 when converted to a 32-bit signed
integer. Since the loop in unparse_something() only runs as long as its
input is greater than zero, this will result in nothing being printed to
the buffer. Changing unparse_flags() to take an int64_t avoids this
behaviour, at least until a 64th flag bit is added. We also return an
error value of -1 from unparse_something() if it receives a negative
value.

However, the callers are not checking the result from unparse_flags()
and would still have attempted to log these uninitialised bytes. Modify
some of these callers so that they perform this checking.

2021-12-03 13:58 UTC, jaltman requested changes
I'm unsure that returning -1 from unparse_something() is needed.  The reason that there are few if any error checks from unparse_flags(), unparse_units() and unparse_units_approx() is that n practice they cannot fail.   The return value is the number of bytes copied by snprintf() or that would have been copied by snprintf() if 'len' is zero.  

snprintf() can only return -1 under two circumstances:
 1. 'len' is greater than INT_MAX
 2. 'len' is zero and the space required to copy the string including the terminating NUL is greater than INT_MAX.   

In addition, the return value of unparse_units() while its an 'int' is then converted to 'size_t' higher in the food chain.   So a negative value returned here will be treated as a large unsigned integer.

What I would prefer to see is an assertion that 'num' is not negative.

2021-12-03 17:07 UTC, abartlet commented
Thanks for the feedback.  This, like #869 was some patches that @josephsutton1 had done over our (antipodean) winter which are not on our critical path but wanted to propose upstream for comment rather than just drop. 

Again, I'll keep this open just for now to track where we are at, but I think both our efforts are best spent elsewhere, we have plenty of meaningful changes to upstream also.

2021-12-03 17:17 UTC, jaltman commented
@abartlet There is a real issue here to fix.   The size of the input variable does need to be increased so proper output is generated.

2021-12-06 04:23 UTC, josephsutton1 commented on lib/roken/parse_units.c
> +    if (num < 0)
To be clear, should this case return a negative error value or produce an assertion failure? The only place I can see the return value being used as a `size_t` is in `parse_time-test.c`, which could be changed to use `int` instead, so it seems like returning an error value shouldn't create additional problems.

2021-12-17 18:28 UTC, nicowilliams commented
The problem here is `unparse_flags()` taking an `int`.  Enlarging that to `int64_t` is nice, but I think we should probably make it a `uint64_t`.  Looking at all calls to `unparse_flags()` I don't see why not do that.  Also, there are a few callers that pass signed ints that will need slight changes.

2021-12-17 18:46 UTC, nicowilliams commented
I'm going to take a crack at finishing this PR.

2021-12-17 21:48 UTC, nicowilliams commented
Another thing is that we're not really checking for truncation in `unparse_flags()` callers...  It's mostly not a problem right now, but I would think we should.  Or, even better, we should have a version of `unparse_flags()` that allocates the string to write to, `asprintf()`-style.

2021-12-17 21:50 UTC, nicowilliams commented
I've force-pushed a version of this to this PR that splits all the parse/unparse units/flags codepaths into signed and unsigned versions, with the signed ones dealing in `int64_t` and the unsigned ones dealing in `uint64_t`.  I made `parse_bytes()` return `ssize_t` (since, after all, it uses `parse_units()`, which returns `int64_t`), and several such differences.

2021-12-18 00:34 UTC, merged